# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'BasicTunnel-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'TunnelKit'
   pod 'Alamofire'
   pod 'SwiftyStoreKit'

  # Pods for BasicTunnel-iOS

end


target 'BasicTunnelExtension-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'TunnelKit'





  # Pods for BasicTunnelExtension-iOS

end
